# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
   include:
     - myNewDadApp/

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/$(projectName).csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- template: ../Common/ci-template.yml